### ISSUE TITLE
Use `failure` instead of `std::error::Error`

### ISSUE THREAD

**Issue by ipetkov** [ipetkov/conch-parser#1]
* Migrate `ParseError` and any other errors in this crate to using `failure`: instead of implementing `std::error::Error` we should just implement `failure::Fail` instead

https://crates.io/crates/failure
https://crates.io/crates/failure_derive

**Comment by quark-zju** [comment]
The error eco-system has changed. Now the best practice for a library might be just defining concrete error types implementing std error, optionally using `thiserror` to simplify the code. `anyhow` is considered a better solution for the "trait object" errors more suitable for application use-cases. Using `failure` (or `anyhow`) would require upstream code to also use the same non-std non-static error types.

**Comment by ipetkov** [comment]
Thanks for the note, you're right! This was a left over reminder from several years ago, so I'm going to close it since it's no longer relevant
